char *_strcat(char *dest, char *src);
int _strcmp(char *s1, char *s2);
char *_strncpy(char *dest, char *src, int n);
char *_strncat(char *dest, char *src, int n);
int _putchar(char c);
int _islower(int c);
int _isalpha(int c);
int _abs(int);
int _isupper(int c);
int _isdigit(int c);
char *_strcpy(char *dest, char *src);
void _puts(char *str);
int _strlen(char *s);
char *_memset(char *s, char b, unsigned int n);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_strchr(char *s, char c);
unsigned int _strspn(char *s, char *accept);
char *_strpbrk(char *s, char *accept);
char *_strstr(char *haystack, char *needle);
int _atoi(char *s);
